agenda/urls.py
from django.urls import path

from . import views

app_name = 'agenda'

urlpatterns = [
    path('create/', views.ContatoCreateView.as_view(), name='create'),
    path('list/', views.ContatoListView.as_view(), name='list'),
    path('update/<int:id>/', views.ContatoUpdateView.as_view(), name='update'),
    path('delete/<int:id>/', views.ContatoDeleteView.as_view(), name='delete'),
    path('gerador/', views.GeradorDeContatoView.as_view(), name='gerador'),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('__debug__/', include('debug_toolbar.urls')),
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('agenda/', include('agenda.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.HomeView.as_view(), name='index'),
]

agenda/models.py
from django.db import models

from users.models import User


def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return "user_{0}/photos/{1}".format(instance.user.first_name, filename)


class Contato(models.Model):
    user = models.ForeignKey(
        verbose_name='Usuário',
        to=User,
        on_delete=models.CASCADE,
        blank=True
    )
    nome = models.CharField(
        verbose_name='Nome',
        max_length=150,
        blank=False,
        null=True
    )
    sobrenome = models.CharField(
        verbose_name='Sobrenome',
        max_length=150,
        blank=False,
        null=True
    )
    telefone = models.CharField(
        verbose_name='Telefone',
        max_length=13,
        blank=False,
        null=True
    )
    email = models.EmailField(
        verbose_name='Email',
        max_length=255,
        unique=True,
        blank=True,
        null=True
    )
    imagem = models.ImageField(
        verbose_name='Foto',
        upload_to=user_directory_path,
        default='user.png'
    )

    def nome_completo(self) -> str:
        frase = f'{self.nome} {self.sobrenome}'
        return frase

    def __str__(self) -> str:
        return f'{self.nome} {self.sobrenome}'

    class Meta:
        verbose_name = 'Contato'
        verbose_name_plural = 'Contatos'
        ordering = ['user', 'nome']

home/models.py
from django.db import models

# Create your models here.

users/models.py
import uuid

from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    id = models.UUIDField(
        verbose_name=_('ID'),
        primary_key=True,
        editable=False,
        default=uuid.uuid4
    )
    email = models.EmailField(
        verbose_name=_('Email'),
        unique=True,
        blank=False,
        null=True
    )
    telefone = models.CharField(
        max_length=20,
        verbose_name=_('Phone Number'),
        blank=True,
        null=True
    )
    data_nascimento = models.DateField(
        verbose_name=_('Data de Nascimento'),
        blank=False,
        null=True
    )

    def __str__(self) -> str:
        return self.get_full_name()

    def save(self, *args, **kwargs):
        # Verifique se o username está vazio (None) e se o email está definido
        if not self.username and self.email:
            self.username = self.email
        super().save(*args, **kwargs)

    # Defina o campo email como o campo de nome de usuário
    USERNAME_FIELD = 'email'
    # Defina quais campos serão obrigatórios ao criar um usuário
    REQUIRED_FIELDS = ['first_name', 'last_name', 'username']

    class Meta:
        verbose_name = _('User')
        verbose_name_plural = _('Users')
        ordering = ['first_name', ]
        indexes = [
            models.Index(fields=['email']),
            models.Index(fields=['telefone']),
            models.Index(fields=['data_nascimento']),
        ]

agenda/forms.py
from django import forms

from .models import Contato


class GeradorContatoForm(forms.Form):
    qtd = forms.IntegerField(
        widget=forms.NumberInput,
        label='Quantidade de Contatos'
    )


class ContatoForm(forms.ModelForm):
    class Meta:
        model = Contato
        fields = [
            'nome', 'sobrenome',
            'telefone', 'email', 'imagem'
        ]
        widgets = {
            'nome': forms.TextInput,
            'sobrenome': forms.TextInput,
            'telefone': forms.TextInput,
            'email': forms.EmailInput
        }
        labels = {
            'nome': 'Nome',
            'sobrenome': 'Sobrenome',
            'telefone': 'Telefone',
            'email': 'Email'
        }

agenda/views.py
from django.contrib import messages
from django.shortcuts import get_object_or_404, redirect, render
from django.views import View

from .forms import ContatoForm, GeradorContatoForm
from .models import Contato
from .utils.scripts.make_db import make_contatos


class GeradorDeContatoView(View):
    def get(self, request):
        form = GeradorContatoForm()
        ctx = {
            'form': form
        }
        return render(request, 'agenda/pages/gerador.html', ctx)

    def post(self, request):
        POST = request.POST
        qtd = int(POST['qtd'])
        make_contatos(qtd, request)
        messages.success(request, f'{qtd} Contatos Criados!')
        return redirect('agenda:gerador')


class ContatoListView(View):
    def get(self, request):
        contatos = Contato.objects.filter(
            user=request.user
        ).all().select_related('user')
        ctx = {
            'contatos': contatos
        }
        return render(request, 'agenda/pages/contatos_list.html', ctx)


class ContatoCreateView(View):
    def get(self, request):
        form = ContatoForm()
        ctx = {
            'form': form
        }
        return render(request, 'agenda/pages/contatos_create.html', ctx)

    def post(self, request):
        form = ContatoForm(request.POST or None)
        if form.is_valid():
            contato = form.save(commit=False)
            contato.user = request.user
            contato.save()
            messages.success(request, 'Contato Salvo com Sucesso!')
            return redirect('agenda:create')


class ContatoUpdateView(View):
    def get(self, request, id):
        contato = Contato.objects.get(id=id)
        form = ContatoForm(instance=contato)
        ctx = {
            'contato': contato,
            'form': form
        }
        return render(request, 'agenda/pages/contatos_update.html', ctx)

    def post(self, request, id):
        contato = Contato.objects.get(id=id)
        form = ContatoForm(request.POST or None, instance=contato)
        if form.is_valid():
            form.save()
            messages.success(request, 'Contato atualizado com sucesso!')
            return redirect('agenda:list')
        else:
            ctx = {
                'contato': contato,
                'form': form
            }
            messages.error(request, 'Houve um erro ao editar o contato')
            return render(request, 'agenda/pages/contatos_update.html', ctx)


class ContatoDeleteView(View):
    def get(self, request, id):
        contato = get_object_or_404(Contato, id=id)
        ctx = {
            'contato': contato,
        }
        return render(request, 'agenda/pages/contatos_delete.html', ctx)

    def post(self, request, id):
        contato = get_object_or_404(Contato, id=id)
        contato.delete()
        messages.success(request, 'Contato apagado com sucesso!')
        return redirect('agenda:list')

home/views.py
from django.shortcuts import render
from django.views import View


class HomeView(View):
    def get(self, request):
        return render(request, 'home/pages/home.html')

agenda/templates/agenda/pages/contatos_create.html
{% extends 'global/base.html' %}
{% block title %}Create{% endblock title %}
{% block content %}
{% if messages %}
{% include 'global/partials/messages.html' %}
{% endif %}
<h1 class='title'>Crie um novo contato</h1>
<div class="form_div">
    <form action="{% url 'agenda:create' %}" method="post">
        {% csrf_token %}
        {% for field in form %}
        <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label }}:</label>
            {{ field }}
        </div>
        {% endfor %}
        <button class='btn-s' type="submit">Criar</button>
    </form>
</div>
<a class='btn-p' href="{% url 'agenda:list' %}">Voltar</a>
{% endblock content %}

agenda/templates/agenda/pages/contatos_delete.html
{% extends 'global/base.html' %}
{% block title %}Delete{% endblock title %}
{% block content %}
{% if messages %}
{% include 'global/partials/messages.html' %}
{% endif %}
<h1 class='title'>Apagar o Contato: {{ contato.nome_completo }}</h1>
<div class="delete">
    <h3>Tem certeza que deseja apagar o contato?</h3>
    <form action="{% url 'agenda:delete' contato.id %}" method="post">
        {% csrf_token %}
        <button class='btn-s' type="submit">Apagar</button>
    </form>
</div>
<a class='btn-p' href="{% url 'agenda:list' %}">Voltar</a>
{% endblock content %}

agenda/templates/agenda/pages/contatos_list.html
{% extends 'global/base.html' %}
{% block title %}List{% endblock title %}
{% block content %}
{% if messages %}
{% include 'global/partials/messages.html' %}
{% endif %}
<h1 class='title'>Todos os Contatos de {{ request.user.get_full_name }}</h1>
<div class="contato_list">
  {% for contato in contatos %}
    <div class="contact">
      <div class="top_card">
        {% comment %} <img src="{{ contato.imagem.url }}" alt=""> {% endcomment %}
        <h1>{{ contato.nome_completo }}</h1>
      </div>
      <div class="mid_card">
        <p><strong>Nome:</strong> {{ contato.nome }}</p>
        <p><strong>Sobreome:</strong> {{ contato.sobrenome }}</p>
        <p><strong>Telefone:</strong> {{ contato.telefone }}</p>
        <p><strong>Email:</strong> {{ contato.email }}</p>
      </div>
      <div class="bottom_card">
        <a class='btn-s' href="{% url 'agenda:update' contato.id %}">Editar</a>
        <a class='btn-s' href="{% url 'agenda:delete' contato.id %}">Apagar</a>
      </div>
    </div>
  {% endfor %}
</div>
{% endblock content %}

agenda/templates/agenda/pages/contatos_update.html
{% extends 'global/base.html' %}
{% block title %}Update{% endblock title %}
{% block content %}
{% if messages %}
{% include 'global/partials/messages.html' %}
{% endif %}
<h1 class='title'>Editar Informações do {{ contato.nome_completo }}</h1>
<div class="form_div">
    <form action="{% url 'agenda:update' contato.id %}" method="post">
        {% csrf_token %}
        {% for field in form %}
        <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label }}:</label>
            {{ field }}
            {% if field.help_text %}
            {{ field.help_text }}
            {% endif %}
            {{ field.errors }}
        </div>
        {% endfor %}
        <button class='btn-s' type="submit">Salvar</button>
    </form>
</div>
<a class='btn-p' href="{% url 'agenda:list' %}">Voltar</a>
{% endblock content %}

agenda/templates/agenda/pages/gerador.html
{% extends 'global/base.html' %}
{% block title %}Gerador{% endblock title %}
{% block content %}
{% if messages %}
{% include 'global/partials/messages.html' %}
{% endif %}
<h1 class='title'>Crie Contatos Fakes</h1>
<div class="form_div">
    <form action="{% url 'agenda:gerador' %}" method="post">
        {% csrf_token %}
        {% for field in form %}
        <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label }}:</label>
            {{ field }}
        </div>
        {% endfor %}
        <button class='btn-s' type="submit">Criar</button>
    </form>
</div>
<a class='btn-p' href="{% url 'agenda:list' %}">Voltar</a>
{% endblock content %}

home/templates/home/pages/home.html
{% extends 'global/base.html' %}
{% block title %}Home{% endblock title %}
{% block content %}
<h1>Home</h1>
{% endblock content %}